(function () {
  'use strict';
  var sefirot = [
    { name: 'Kéter', title: 'Corona', intro: 'Intención, origen y conciencia de unidad.', details: { significado: 'Eres la chispa divina pura antes de tomar forma. Representa la conexión más alta de tu ser con el universo, el punto donde tu voluntad individual se disuelve en el todo. Es el "Yo Soy" incondicional, la inspiración repentina y pura.', aplicacion: 'Busca momentos de silencio absoluto. Antes de cualquier acción importante, conecta con tu intención original: ¿Por qué haces lo que haces? Reconoce que eres parte de algo mucho más vasto.', sombra: 'Sentirte desconectado de la realidad, vivir en las nubes, la soberbia espiritual de creer que ya lo sabes todo, o la parálisis por exceso de abstracción.' } },
    { name: 'Jojmá', title: 'Sabiduría', intro: 'Intuición creadora y visión inicial.', details: { significado: 'El destello del genio, el relámpago de intuición. Jojmá es la energía masculina primordial, la semilla de todas las ideas. Es ese instante de "¡Eureka!" antes de que la idea empiece a tener límites o forma.', aplicacion: 'Permite que la inspiración fluya sin juzgarla ni intentar estructurarla de inmediato. Confía en tus primeras intuiciones y anota las ideas locas antes de que la lógica las descarte.', sombra: 'Caos mental, incapacidad para concretar absolutamente nada, empezar mil proyectos y no terminar ninguno porque saltas a la siguiente gran idea.' } },
    { name: 'Biná', title: 'Entendimiento', intro: 'Forma, discernimiento y comprensión.', details: { significado: 'La matriz cósmica, la energía femenina que recibe el destello de Jojmá y le da forma, estructura y viabilidad. Es la capacidad de discernir, organizar y entender profundamente cómo funciona algo.', aplicacion: 'Toma tus ideas volátiles y ponles límites. Crea planes de acción, establece horarios y define qué recursos necesitas. Es el momento de ser pragmático e inteligente.', sombra: 'Rigidez mental severa, burocracia paralizante, obsesión por el control de los detalles que mata la inspiración original (Jojmá).' } },
    { name: 'Jésed', title: 'Misericordia', intro: 'Generosidad, expansión y confianza.', details: { significado: 'El amor incondicional que fluye sin límites. Es el deseo ardiente de dar, de compartir, de expandirse y abrazar al mundo. Representa la gracia, el optimismo y la benevolencia pura.', aplicacion: 'Practica la generosidad sin esperar nada a cambio. Ábrete a dar afecto, dinero o tiempo. Confía en la bondad inherente de la vida y permite que tu corazón se expanda.', sombra: 'Dar hasta vaciarte, incapacidad para decir "no", amor asfixiante, codependencia o tolerar abusos por una mal entendida compasión.' } },
    { name: 'Guevurá', title: 'Fuerza', intro: 'Límite, rigor y capacidad de elegir.', details: { significado: 'El poder del límite y el rigor. Guevurá es la fuerza que restringe el flujo infinito de Jésed para que el mundo no se inunde. Es la ley, la justicia, el juicio crítico y la capacidad de poner frenos sanos.', aplicacion: 'Aprende a decir "NO". Establece límites claros para proteger tu energía. Aplica disciplina a tus rutinas y evalúa las situaciones con rigor y objetividad.', sombra: 'Crueldad despiadada, tiranía, ser excesivamente crítico contigo mismo y con los demás, represión emocional o paralizarse por miedo al castigo.' } },
    { name: 'Tiféret', title: 'Belleza', intro: 'Centro, integración y equilibrio del corazón.', details: { significado: 'El corazón del Árbol, donde la generosidad expansiva de Jésed y los límites estrictos de Guevurá encuentran la perfecta armonía. Es la belleza que surge del equilibrio. Representa la autenticidad, la verdad personal y la compasión sanadora.', aplicacion: 'Actúa desde el centro de tu pecho. Equilibra tu necesidad de dar con tu necesidad de cuidarte. Muestra tu verdadero yo al mundo con valentía y belleza.', sombra: 'Egocentrismo desmesurado, creer que eres el centro del universo, vanidad extrema o intentar complacer a todos sacrificando tu propia verdad.' } },
    { name: 'Nétsaj', title: 'Victoria', intro: 'Deseo, perseverancia y movimiento.', details: { significado: 'La fuerza de los instintos, el fuego de la pasión y la resistencia emocional. Es el motor que te empuja a triunfar y a superar los obstáculos emocionales. Representa el impulso artístico y el romance.', aplicacion: 'Conecta con lo que realmente deseas a nivel visceral. Usa esa pasión como combustible para perseverar cuando las cosas se pongan difíciles. Atrévete a desear el triunfo.', sombra: 'Impulsividad destructiva, ser esclavo de tus pasiones, manipulación emocional dramática o buscar la victoria pisoteando a los demás.' } },
    { name: 'Hod', title: 'Esplendor', intro: 'Lenguaje, análisis y reconocimiento de patrones.', details: { significado: 'El intelecto estructurado, la lógica fría y la comunicación precisa. Hod organiza el fuego de Nétsaj a través del lenguaje, la ciencia y la estrategia. Es el recipiente mental por donde fluye la verdad.', aplicacion: 'Analiza tu situación con lógica. Organiza tus pensamientos y comunícalos con absoluta claridad. Estudia, investiga y planifica tus movimientos con astucia.', sombra: 'Mentira calculada, usar el intelecto para engañar, cinismo, desconexión total de las emociones, o perderse en la teoría olvidando la acción.' } },
    { name: 'Yesod', title: 'Fundamento', intro: 'Imaginación, memoria y mundo interior.', details: { significado: 'El mundo del inconsciente, los sueños y la imaginación. Es la matriz final que recoge la energía de todas las sefirot superiores antes de materializarla en el mundo físico. Es la base de nuestra identidad psíquica.', aplicacion: 'Presta atención a tus sueños e intuiciones instintivas. Limpia tu imaginación de miedos (porque Yesod materializa lo que imaginas) y enfócate en visualizar lo que sí quieres.', sombra: 'Perderse en fantasías delirantes, vivir de ilusiones, autoengaño profundo, mentiras o quedarse atrapado en memorias traumáticas del pasado.' } },
    { name: 'Maljut', title: 'Reino', intro: 'Presencia, acción y encarnación en lo cotidiano.', details: { significado: 'La realidad física, tu cuerpo, la Tierra. Maljut no emana luz propia, recibe y manifiesta toda la luz del Árbol en forma tangible. Es el aquí y el ahora. Es el final del proceso creativo y el inicio del retorno.', aplicacion: 'Baja a tierra. Ejecuta, actúa, concreta. De nada sirve la sabiduría si no la aplicas en el plano físico. Cuida tu cuerpo, paga tus cuentas, organiza tu entorno y vive el presente.', sombra: 'Materialismo extremo, pesadez, depresión que te ancla a la cama, negar lo espiritual pensando que solo existe lo que puedes tocar o medir.' } }
  ];
  function slugify(text) {
    return text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  }

  var app = document.getElementById('kabbalah-app');
  app.innerHTML = '<header class="view-header"><p class="eyebrow">✦ MAPA DE SIGNIFICADOS ✦</p><h1>Árbol de la Vida</h1><p class="subtitle">Una introducción contemplativa a las diez sefirot y a sus preguntas de equilibrio.</p></header>' +
    '<section class="panel tree-intro"><div class="card-image-wrap tree-banner-wrap"><img src="images/cabala/arbol-de-la-vida.jpg" alt="El Árbol de la Vida Cósmico" class="card-image" onerror="this.parentElement.style.display=\'none\'"></div><p class="section-kicker">DOS MARCOS QUE NO DEBEN CONFUNDIRSE</p><h2>Tradición y lectura simbólica</h2><p class="muted">La Cábala judía es una tradición religiosa e histórica con sus propios textos y prácticas. El Árbol de la Vida hermético es una interpretación esotérica posterior que relaciona sefirot, tarot, planetas y otros símbolos. Esta página ofrece una introducción cultural, no una representación completa de ninguna de las dos tradiciones.</p></section>' +
    '<section class="tarot-grid" aria-label="Diez sefirot">' + sefirot.map(function (item, index) {
      var slug = slugify(item.name);
      return '<article class="tarot-card">' +
        '<div class="card-image-wrap tarot-image-wrap"><img src="images/cabala/sefira-' + slug + '.jpg" alt="' + item.name + '" class="card-image tarot-img" onerror="this.parentElement.style.display=\'none\'"></div>' +
        '<div class="tarot-content-wrap"><span class="tarot-number">0' + (index + 1) + '</span><p class="section-kicker">' + item.title.toUpperCase() + '</p><h2>' + item.name + '</h2>' +
        '<div class="tarot-details"><h3>✦ El Significado Espiritual</h3><p>' + item.details.significado + '</p><h3>✦ Aplicación Práctica</h3><p>' + item.details.aplicacion + '</p><h3>✦ La Sombra (Desequilibrio)</h3><p>' + item.details.sombra + '</p></div>' +
        '<div class="tarot-reflection"><label>Pregunta para contemplar <textarea rows="2" data-sefira="' + item.name + '" placeholder="Escribe una observación..."></textarea></label></div></div></article>';
    }).join('') + '</section>' +
    '<section class="panel esoteric-panel"><p class="section-kicker">CONTINÚA EXPLORANDO</p><div class="esoteric-actions"><a class="button" href="numerologia.html">Ver numerología</a><a class="button secondary" href="tarot.html">Abrir Tarot</a><a class="button secondary" href="lecturas.html">Mis lecturas</a></div></section>';

  var stored = {};
  try { stored = JSON.parse(localStorage.getItem('your-life-data') || '{}'); } catch (error) {}
  var notes = stored.kabbalahNotes || {};
  document.querySelectorAll('[data-sefira]').forEach(function (field) {
    field.value = notes[field.dataset.sefira] || '';
    field.addEventListener('input', function () {
      notes[field.dataset.sefira] = field.value;
      stored.kabbalahNotes = notes;
      localStorage.setItem('your-life-data', JSON.stringify(stored));
    });
  });
})();