(function () {
  'use strict';
  var api = window.YourLifeAPI, data = readData(), dob = data.dob ? new Date(data.dob.year, data.dob.month, data.dob.day) : null;
  var country = document.getElementById('country'), city = document.getElementById('city'), status = document.getElementById('world-status'), autoRefresh = document.getElementById('auto-refresh');
  var refreshInterval = 5 * 60 * 1000, lastPopulation = null, lastPopulationAt = null;
  var signs = [{ name: 'Capricornio', start: [1, 1], end: [1, 19] }, { name: 'Acuario', start: [1, 20], end: [2, 18] }, { name: 'Piscis', start: [2, 19], end: [3, 20] }, { name: 'Aries', start: [3, 21], end: [4, 19] }, { name: 'Tauro', start: [4, 20], end: [5, 20] }, { name: 'Géminis', start: [5, 21], end: [6, 20] }, { name: 'Cáncer', start: [6, 21], end: [7, 22] }, { name: 'Leo', start: [7, 23], end: [8, 22] }, { name: 'Virgo', start: [8, 23], end: [9, 22] }, { name: 'Libra', start: [9, 23], end: [10, 22] }, { name: 'Escorpio', start: [10, 23], end: [11, 21] }, { name: 'Sagitario', start: [11, 22], end: [12, 21] }, { name: 'Capricornio', start: [12, 22], end: [12, 31] }];
  function readData() { try { return JSON.parse(localStorage.getItem('your-life-data') || '{}'); } catch (error) { return {}; } }
  function escapeHtml(value) { return String(value || '').replace(/[&<>"']/g, function (character) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character]; }); }
  function sign(date) { if (!date) return 'tu signo'; var key = [date.getMonth() + 1, date.getDate()]; return signs.find(function (item) { return key[0] === item.start[0] && key[1] >= item.start[1] || key[0] === item.end[0] && key[1] <= item.end[1]; }).name; }
  function moon(date) { var known = new Date(Date.UTC(2000, 0, 6, 18, 14)), days = ((date || new Date()).getTime() - known.getTime()) / 86400000, phase = ((days % 29.530588853) + 29.530588853) % 29.530588853; return { age: phase, name: phase < 1.85 || phase > 27.68 ? 'Luna nueva' : phase < 7.38 ? 'Creciente' : phase < 14.76 ? 'Gibosa creciente' : phase < 16.61 ? 'Luna llena' : phase < 22.14 ? 'Gibosa menguante' : phase < 23.99 ? 'Cuarto menguante' : 'Menguante' }; }
  function metric(value, text) { return '<article class="metric"><strong>' + value + '</strong><span>' + text + '</span></article>'; }
  function stamp(source) { return '<small class="api-source">Fuente: ' + escapeHtml(source) + ' · actualizado ' + new Date().toLocaleTimeString('es', { hour: '2-digit', minute: '2-digit' }) + '</small>'; }
  function projection(result) {
    var sourceYear = Number(result.year) || new Date().getFullYear(), current = new Date(), sourceDate = new Date(sourceYear, 0, 1), daysSinceSource = Math.max(0, (current - sourceDate) / 86400000), netRate = (Number(result.birthRate || 0) - Number(result.deathRate || 0)) / 1000;
    return Number(result.population) + netRate * Number(result.population) * daysSinceSource / 365.25;
  }
  function renderPopulation(result) { var elapsedSinceFetch = lastPopulationAt ? (Date.now() - lastPopulationAt) / 86400000 : 0, projectedNow = projection(result), netRate = (Number(result.birthRate || 0) - Number(result.deathRate || 0)) / 1000, population = projectedNow + netRate * projectedNow * elapsedSinceFetch / 365.25, current = new Date(), startOfYear = new Date(current.getFullYear(), 0, 1), dayOfYear = Math.max(1, Math.ceil((current - startOfYear) / 86400000)), birthsPerDay = population * Number(result.birthRate || 0) / 1000 / 365.25, deathsPerDay = population * Number(result.deathRate || 0) / 1000 / 365.25, birthsThisYear = birthsPerDay * dayOfYear, deathsThisYear = deathsPerDay * dayOfYear, maleShare = result.male && result.female ? result.male / (result.male + result.female) * 100 : null, femaleShare = maleShare === null ? null : 100 - maleShare; document.getElementById('population-output').innerHTML = metric(Math.round(population).toLocaleString('es'), 'proyección continua ' + current.getFullYear() + ' (base oficial ' + result.year + ')') + metric(Math.round(birthsThisYear).toLocaleString('es'), 'nacimientos proyectados en ' + current.getFullYear()) + metric(Math.round(deathsThisYear).toLocaleString('es'), 'fallecimientos proyectados en ' + current.getFullYear()) + metric(Math.round(birthsPerDay).toLocaleString('es'), 'nacimientos proyectados hoy') + metric(Math.round(deathsPerDay).toLocaleString('es'), 'fallecimientos proyectados hoy') + metric(Math.round(Math.max(0, birthsPerDay - deathsPerDay)).toLocaleString('es'), 'crecimiento proyectado diario') + metric(maleShare === null ? 'N/D' : maleShare.toFixed(1) + '%', 'población masculina estimada') + metric(femaleShare === null ? 'N/D' : femaleShare.toFixed(1) + '%', 'población femenina estimada') + metric(result.migration === null || result.migration === undefined ? 'N/D' : Math.round(Number(result.migration) / 365.25).toLocaleString('es'), 'migración neta diaria') + stamp(result.source); }
  function loadPopulation() { status.textContent = 'Consultando población...'; return api.getPopulation(country.value).then(function (result) { if (!result.population) throw new Error('Sin población'); lastPopulation = result; lastPopulationAt = Date.now(); renderPopulation(result); status.textContent = 'Datos demográficos actualizados.'; }).catch(function () { if (!lastPopulation) document.getElementById('population-output').innerHTML = '<p class="muted">La fuente demográfica no está disponible ahora. Intenta actualizar más tarde.</p>'; status.textContent = 'Algunas fuentes no respondieron; se conserva el último dato válido.'; }); }
  function loadWeather() { var query = city.value.trim(); if (!query) { document.getElementById('weather-output').innerHTML = '<p class="muted">Escribe una ciudad para consultar el clima.</p>'; return Promise.resolve(); } return fetch('https://geocoding-api.open-meteo.com/v1/search?name=' + encodeURIComponent(query) + '&count=1&language=es&format=json').then(function (response) { if (!response.ok) throw new Error('Geocoding'); return response.json(); }).then(function (result) { if (!result.results || !result.results[0]) throw new Error('Ciudad no encontrada'); return api.getWeather(result.results[0].latitude, result.results[0].longitude).then(function (weather) { document.getElementById('weather-output').innerHTML = metric(weather.temperature + ' °C', 'temperatura actual') + metric(weather.humidity + '%', 'humedad relativa') + metric(weather.wind + ' km/h', 'viento') + '<article class="metric"><strong>' + escapeHtml(result.results[0].name) + '</strong><span>' + escapeHtml(result.results[0].country) + '</span></article>'; document.getElementById('weather-updated').textContent = 'Zona horaria: ' + weather.timezone; }); }).catch(function () { document.getElementById('weather-output').innerHTML = '<p class="muted">No se pudo encontrar esa ciudad o consultar su clima.</p>'; }); }
  function loadHistory() { if (!dob) { document.getElementById('history-output').innerHTML = '<p class="muted">Configura tu fecha de nacimiento en el mapa para consultar esta sección.</p>'; return Promise.resolve(); } return api.getHistory(dob.getMonth() + 1, dob.getDate()).then(function (result) { var blocks = [['Acontecimientos', result.events], ['Nacimientos', result.births], ['Fallecimientos', result.deaths]]; document.getElementById('history-output').innerHTML = blocks.map(function (block) { return '<article class="history-api-card"><h3>' + block[0] + '</h3>' + (block[1].length ? '<ul>' + block[1].map(function (item) { return '<li>' + escapeHtml(item.text) + (item.year ? ' <small>(' + item.year + ')</small>' : '') + '</li>'; }).join('') + '</ul>' : '<p class="muted">Sin resultados destacados.</p>') + '</article>'; }).join('') + stamp(result.source); }).catch(function () { document.getElementById('history-output').innerHTML = '<p class="muted">La consulta histórica no está disponible ahora.</p>'; }); }
  function loadImage() { return api.getImage(sign(dob) + ' zodiac symbol').then(function (image) { document.getElementById('image-output').innerHTML = '<img src="' + escapeHtml(image.url) + '" alt="Símbolo de ' + escapeHtml(sign(dob)) + '"><p>' + escapeHtml(image.title) + '</p>' + (image.author ? '<small>Autor: ' + escapeHtml(image.author.replace(/<[^>]*>/g, '')) + '</small>' : '') + stamp(image.source); }).catch(function () { document.getElementById('image-output').innerHTML = '<p class="muted">No se encontró una imagen pública para este signo.</p>'; }); }
  function renderAstronomy() { var phase = moon(new Date()); document.getElementById('astronomy-output').innerHTML = '<div class="moon-visual" style="--moon-phase:' + (phase.age / 29.53 * 100) + '%"></div><h3>' + phase.name + '</h3><p class="muted">Edad lunar aproximada: ' + phase.age.toFixed(1) + ' días</p><small class="api-source">Cálculo astronómico local · actualizado ' + new Date().toLocaleTimeString('es', { hour: '2-digit', minute: '2-digit' }) + '</small>'; }
  function updateAutoRefreshLabel() { if (!autoRefresh) return; var next = new Date(Date.now() + refreshInterval); autoRefresh.textContent = 'Próxima consulta automática: ' + next.toLocaleTimeString('es', { hour: '2-digit', minute: '2-digit' }) + '.'; }
  function refresh() { renderAstronomy(); loadPopulation(); loadWeather(); loadHistory(); loadImage(); document.getElementById('last-updated').textContent = 'Última actualización solicitada: ' + new Date().toLocaleString('es'); updateAutoRefreshLabel(); }
  document.getElementById('load-world').addEventListener('click', refresh); city.addEventListener('keydown', function (event) { if (event.key === 'Enter') refresh(); }); refresh(); setInterval(function () { refresh(); }, refreshInterval); setInterval(function () { if (lastPopulation) renderPopulation(lastPopulation); }, 1000); var guide = document.createElement('script'); guide.src = 'guide.js'; document.body.appendChild(guide);
})();
