(function () {
  'use strict';
  var profile = window.EsotericEngine.calculateProfile();
  var app = document.getElementById('numerology-app');
  var value = function (number) { return number === null ? '—' : number; };
  var displayName = profile.fullName || 'tu perfil';
  var meanings = {
    1: { title: 'El Mago de tu Vida', esencia: 'El número 1 es la pura fuerza de voluntad, el pionero y el líder nato. Representa tu capacidad absoluta para valerte por ti mismo, tomar la iniciativa y abrir caminos donde antes no había nada. Eres una fuerza individualista y sumamente creadora.', leccion: 'Tu mayor desafío es aprender a confiar en ti mismo sin caer en la arrogancia. Debes vencer el miedo al fracaso, evitar volverte un dictador con los demás y recordar que, aunque puedes hacerlo solo, la vulnerabilidad también requiere valentía.' },
    2: { title: 'El Espejo y la Alianza', esencia: 'Eres el diplomático, el pacificador y el cuidador de las relaciones. Tienes una sensibilidad exquisita para leer a los demás y crear armonía. Tu fuerza radica en la cooperación, la empatía y en ser el apoyo invisible pero fundamental que sostiene grandes cosas.', leccion: 'El reto gigante del 2 es no perder su propia identidad por complacer a otros. Tienes que aprender a poner límites claros, no huir de los conflictos necesarios y entender que tu voz es igual de importante que la de los demás.' },
    3: { title: 'El Artista Radiante', esencia: 'La pura expresión, el magnetismo y la alegría de vivir. Eres un canal brillante para la comunicación, el arte, la palabra y la creatividad. El 3 ilumina cualquier lugar al que entra con su entusiasmo contagioso y su encanto magnético.', leccion: 'Tu mente va tan rápido que puedes volverte disperso, superficial o dejar todo a medias. El desafío es la disciplina: enfoca tu energía creativa en un solo punto hasta terminarlo y cuídate del chisme o la exageración dramática.' },
    4: { title: 'El Arquitecto', esencia: 'La estabilidad, el trabajo duro y los cimientos indestructibles. Eres la persona más confiable de la habitación. Construyes imperios a base de orden, lógica y perseverancia. Eres la manifestación práctica de las ideas en el mundo terrenal.', leccion: 'Cuidado con la rigidez mental y la terquedad paralizante. Puedes llegar a ser tan rutinario y estricto que te pierdes de la magia y la fluidez de la vida. Debes aprender a ser flexible y a soltar el control absoluto.' },
    5: { title: 'El Espíritu Libre', esencia: 'Eres el cambio, la aventura, la sensualidad y la libertad pura. Tienes un alma nómada que anhela experimentar todo lo que la vida ofrece. Eres brillante, adaptable, rápido y tremendamente carismático. Tu vida está llena de giros inesperados.', leccion: 'Tu terror al compromiso puede sabotear tu éxito a largo plazo. La libertad no es saltar de flor en flor huyendo de la responsabilidad, sino elegir conscientemente. Cuidado con los excesos y la inestabilidad crónica.' },
    6: { title: 'El Sanador y Guardián', esencia: 'El amor, el hogar y la responsabilidad. Eres el padre o la madre cósmica. Tienes un talento inmenso para sanar, nutrir, aconsejar y crear espacios de belleza y armonía. La gente acude a ti en busca de refugio y sabiduría.', leccion: 'Tu sombra es el martirio y el perfeccionismo asfixiante. A menudo das tanto que te vacías por completo y luego te resientes. Debes aprender a cuidar de ti mismo primero y dejar de intentar "salvar" a quienes no quieren ser salvados.' },
    7: { title: 'El Buscador de la Verdad', esencia: 'El intelecto profundo, el análisis y la vida interior. Eres el sabio, el místico, el investigador que nunca se conforma con respuestas superficiales. Tu mente es un escáner que penetra las mentiras y busca los misterios últimos del universo.', leccion: 'El aislamiento y la desconexión emocional. Puedes volverte tan analítico y solitario que te vuelves cínico y te desconectas del calor humano. Tienes que bajar la guardia y permitirte confiar en la vida y en las personas.' },
    8: { title: 'El Creador de Imperio', esencia: 'El infinito poder personal, el dinero, el éxito material y el liderazgo. Has venido a masterizar el mundo de los negocios, la organización y la abundancia terrenal. Tienes una visión ambiciosa y la fuerza para manifestarla.', leccion: 'La obsesión por el estatus y el control puede volver a un 8 tiránico y adicto al trabajo. Debes aprender que el verdadero poder reside en empoderar a otros, no en aplastarlos, y que tu valor no se mide por tu cuenta bancaria.' },
    9: { title: 'El Alma Vieja', esencia: 'La culminación, la sabiduría global y la compasión universal. Tienes una perspectiva humanitaria inmensa y un corazón dispuesto a ayudar al mundo entero. Eres el cierre de un ciclo, un maestro espiritual y un idealista puro.', leccion: 'Te cuesta horrores dejar ir el pasado y los resentimientos. Tu lección es el perdón absoluto y aprender a cerrar ciclos sin amargura. Además, no debes perderte tratando de salvar al mundo y olvidando salvar tu propia vida.' },
    11: { title: 'El Iluminador (Número Maestro)', esencia: 'Eres un portal de pura intuición e inspiración. Tienes un sistema nervioso altamente sensible y recibes "descargas" de información espiritual que otros no perciben. Has venido a inspirar y sanar a través de revelaciones profundas.', leccion: 'La ansiedad y el colapso nervioso. Cargas con tanta energía eléctrica que puedes desestabilizarte. Tienes que anclarte a la tierra, cuidar mucho tu cuerpo y no dejarte hundir por la carga emocional de tu entorno.' },
    22: { title: 'El Constructor Maestro (Número Maestro)', esencia: 'Tienes el idealismo profundo del 11, combinado con el pragmatismo absoluto del 4. Tus ideas no se quedan en las nubes: tú tienes la capacidad épica de construir sistemas, instituciones o legados que beneficiarán a la humanidad durante generaciones.', leccion: 'El terror al fracaso. Tienes una visión tan masiva de lo que podrías lograr que a menudo te paralizas por la presión. Debes dar el primer paso por más pequeño que sea. Evita la tendencia a querer controlar cada mínimo detalle.' },
    33: { title: 'El Maestro de Maestros (Número Maestro)', esencia: 'La encarnación del amor crístico e incondicional. El 33 busca elevar la consciencia del mundo entero a través del servicio puro, la sanación compasiva y la enseñanza. Eres un canal para el amor más alto que existe.', leccion: 'Cargar el dolor del mundo sobre tus hombros hasta destruirte. Tienes que proteger tu propia energía celosamente, entender que no puedes salvar a todo el mundo e irradiar amor sin sacrificar tu integridad.' }
  };
  function escapeHtml(value) { return String(value).replace(/[&<>"']/g, function (character) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character]; }); }
  var guide = Object.keys(meanings).map(function (number) {
    var item = meanings[number];
    return '<article class="tarot-card">' +
      '<div class="card-image-wrap tarot-image-wrap"><img src="images/numerology/numerology-' + number + '.jpg" alt="Número ' + number + '" class="card-image tarot-img" onerror="this.parentElement.style.display=\'none\'"></div>' +
      '<div class="tarot-content-wrap"><span class="tarot-number">0' + number + '</span><p class="section-kicker">' + item.title.toUpperCase() + '</p><h2>' + number + '</h2>' +
      '<div class="tarot-details"><h3>✦ Tu Esencia Numérica</h3><p>' + item.esencia + '</p><h3>✦ Desafíos y Lecciones</h3><p>' + item.leccion + '</p></div></div></article>';
  }).join('');

  app.innerHTML = '<header class="view-header"><p class="eyebrow">✦ MAPA NUMÉRICO ✦</p><h1>Numerología</h1><p class="subtitle">Una lectura simbólica de los números presentes en tu nombre y tu fecha. Perfil actual: <strong>' + escapeHtml(displayName) + '</strong>.</p></header>' +
    '<section class="stats esoteric-stats">' +
      '<article><strong>' + value(profile.lifePath) + '</strong><span>Camino de vida</span></article>' +
      '<article><strong>' + value(profile.expression) + '</strong><span>Expresión</span></article>' +
      '<article><strong>' + value(profile.soulUrge) + '</strong><span>Alma</span></article>' +
      '<article><strong>' + value(profile.personality) + '</strong><span>Personalidad</span></article>' +
      '<article><strong>' + value(profile.personalYear) + '</strong><span>Año personal</span></article>' +
    '</section>' +
    '<section class="stats numerology-secondary-stats">' +
      '<article><strong>' + value(profile.birthDay) + '</strong><span>Día de nacimiento</span></article>' +
      '<article><strong>' + value(profile.attitude) + '</strong><span>Actitud</span></article>' +
      '<article><strong>' + value(profile.maturity) + '</strong><span>Madurez</span></article>' +
    '</section>' +
    '<section class="panel esoteric-panel"><p class="section-kicker">GUÍA DE SIGNIFICADOS</p><div class="tarot-grid">' + guide + '</div></section>' +
    '<section class="panel esoteric-panel"><p class="section-kicker">CÓMO LEERLO</p><h2>Los números son preguntas, no sentencias</h2><p class="muted">Esta lectura usa reducción numerológica pitagórica y conserva los números maestros 11, 22 y 33. Úsala como una herramienta de reflexión personal, no como una predicción ni como consejo médico, financiero o legal.</p></section>' +
    '<section class="panel esoteric-panel"><p class="section-kicker">SIGUIENTE PASO</p><div class="esoteric-actions"><a class="button" href="tarot.html">Abrir Tarot</a><a class="button secondary" href="fecha.html">Volver a tu fecha</a></div></section>';
})();